# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Jeffrey Mabazza
title: PHP Backend Developer
email: jeffreymabazza@gmail.com
#phone: Your phone number (optional)
#website: Your website (eg. https://google.com)(optional)

# Social links
#twitter_username: jekyllrb
github_username:  jeffreymabazza
#dribbble_username: jekyll
facebook_username: jeffrey.mabazza
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: https://ph.linkedin.com/in/jeffrey-mabazza-06a999112
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: assets/my-pic.png
about_content: | # this will include new lines to allow paragraphs
  To be able to contribute to the organization with my competencies and at the same time continue to develop myself professionally in the field of web development.
  
  Key Attributes
    Love and passion for web things
    Well-versed in Internet and web technologies
    Can work on multiple projects simultaneously
    Organized and has a clear development process
    Team player, always willing to support team efforts

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  - PHP
  - MySQL
  - Linux
  - Apache
  - Nginx

# Acheivments and Seminars
achievements_seminars_content: |
  LaraCon 2015
  Laracon 2016
  Laracon 2017


# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
